# Generated by Django 4.0.3 on 2022-05-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecafe', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.CharField(max_length=100, null=True)),
                ('Subject', models.CharField(max_length=100, null=True)),
                ('syllabus', models.CharField(max_length=100, null=True)),
                ('Study_Material', models.CharField(max_length=100, null=True)),
                ('Mock_Test', models.CharField(max_length=100, null=True)),
                ('Project', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
