# Generated by Django 4.0.3 on 2022-05-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecafe', '0003_material'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='addStudent',
        ),
    ]
