# Generated by Django 4.0.3 on 2022-05-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecafe', '0004_rename_student_addstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='Contact_No',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='Course',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='Semester',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='Staff_Id',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='Staff_Name',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='Upload_photo',
        ),
        migrations.AddField(
            model_name='faculty',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='username',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
