# Generated by Django 4.0.3 on 2022-05-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecafe', '0006_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='facultyreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff_Id', models.CharField(max_length=100, null=True)),
                ('Staff_Name', models.CharField(max_length=100, null=True)),
                ('Address', models.CharField(max_length=100, null=True)),
                ('Email', models.CharField(max_length=100, null=True)),
                ('Contact_No', models.IntegerField(null=True)),
                ('Gender', models.CharField(max_length=100, null=True)),
                ('DOB', models.DateField(null=True)),
                ('Course', models.CharField(max_length=100, null=True)),
                ('Semester', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
