# Generated by Django 4.0.3 on 2022-05-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecafe', '0007_facultyreg_delete_faculty_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addstudent',
            old_name='Upload_photo',
            new_name='password',
        ),
        migrations.AddField(
            model_name='addstudent',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facultyreg',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facultyreg',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
