# Generated by Django 4.0.2 on 2022-06-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecafe', '0008_rename_upload_photo_addstudent_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addstudent',
            name='Aadhar_No',
        ),
        migrations.RemoveField(
            model_name='addstudent',
            name='Cast',
        ),
        migrations.AddField(
            model_name='material',
            name='file',
            field=models.FileField(max_length=400, null=True, upload_to='folder/'),
        ),
    ]
