# Generated by Django 4.0.2 on 2022-06-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecafe', '0009_remove_addstudent_aadhar_no_remove_addstudent_cast_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='file',
        ),
        migrations.AlterField(
            model_name='material',
            name='Study_Material',
            field=models.FileField(max_length=400, null=True, upload_to='folder/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='syllabus',
            field=models.FileField(max_length=400, null=True, upload_to='folder/'),
        ),
    ]
