# Generated by Django 4.0.2 on 2022-06-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecafe', '0010_remove_material_file_alter_material_study_material_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='material',
            new_name='materialup',
        ),
    ]
