# Generated by Django 3.1.7 on 2022-07-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecafe', '0013_auto_20220729_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialup',
            name='syllabus',
            field=models.FileField(default=1, max_length=400, upload_to='folder/'),
            preserve_default=False,
        ),
    ]
