# Generated by Django 3.1.7 on 2022-07-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecafe', '0014_auto_20220729_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialup',
            name='syllabus',
            field=models.FileField(max_length=400, null=True, upload_to='folder/'),
        ),
    ]
