# Generated by Django 3.1.7 on 2022-07-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecafe', '0015_auto_20220729_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialup',
            name='Study_Material',
            field=models.FileField(default=1, upload_to='folder/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialup',
            name='syllabus',
            field=models.FileField(default=1, upload_to='folder/'),
            preserve_default=False,
        ),
    ]
